# Generated by Django 6.0.7 on 2026-08-02 08:46

import martor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twisted_site', '0007_project_hackatime_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='content',
            field=martor.models.MartorField(),
        ),
    ]
